services:
  backend:
    build:
      context: .
    container_name: star-backend
    volumes:
      - ./backend/storage:/var/www/html/storage
      - app-public:/var/www/html/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/app/database.sqlite
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: star-nginx
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-public:/var/www/html/public:ro
      - ./backend/storage:/var/www/html/storage:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  app-public:
